In [1]:
"""Матрицы и действия над ними."""

'Матрицы и действия над ними.'

Матрица - это прямоугольная таблица чисел. 

Транспонированная матрица - это матрица, в которой столбцы и строки меняются местами: 1 строка становится 1 столбцом, 2 строка становится вторым столбцом и т.д.

Определитель матрицы - это число, характеризующее ее свойства. 

In [3]:
# код для транспонирования матрицы 4х5
import numpy as np  

A = np.array([
   [1, 2, 5, 6, 0],
   [7, 2, -4, 1, 7],
   [10, -4, 1, 0, 9],
   [-8, 2, 1, -7, 8] 
])

print("Исходная матрица:")
print(A) 

# транспонирование
A_T = A.T 

print("\nТранспонированная матрица:")
print(A_T)


Исходная матрица:
[[ 1  2  5  6  0]
 [ 7  2 -4  1  7]
 [10 -4  1  0  9]
 [-8  2  1 -7  8]]

Транспонированная матрица:
[[ 1  7 10 -8]
 [ 2  2 -4  2]
 [ 5 -4  1  1]
 [ 6  1  0 -7]
 [ 0  7  9  8]]
